name: Context examples
on: [push, pull_request]

jobs:
  my_context:
    runs-on: ubuntu-latest
    steps:
      - name: "My step"
        env:
          MY_ACTION: ${{ github.action }}
        run: echo $MY_ACTION

